name: Build and Release
on:
  release:
    types: [published, prereleased]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: pip install poetry
    
    - name: Build wheel
      run: poetry build
    
    - name: Get wheel filename
      id: wheel-name
      run: |
        WHEEL_FILE=$(ls dist/*.whl | head -1)
        echo "filepath=$WHEEL_FILE" >> $GITHUB_OUTPUT
        echo "filename=$(basename $WHEEL_FILE)" >> $GITHUB_OUTPUT
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.wheel-name.outputs.filepath }}
        asset_name: ${{ steps.wheel-name.outputs.filename }}
        asset_content_type: application/zip
    
    - name: Upload artifacts (for manual testing)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: wheel-files
        path: dist/